---
- name: "roles/bench.supervisor/tasks/main: Create directory"
  file:
    path: /tmp/isucon11-portal
    state: directory

- name: "roles/bench.supervisor/tasks/main: Deploy isucon/isucon11-portal"
  unarchive:
    src: /dev/shm/files-generated/isucon11-portal.tar
    dest: /tmp/isucon11-portal/
    owner: isucon
    group: isucon

- name: "roles/bench.supervisor/tasks/main: Build isuxportal-supervisor"
  become_user: isucon
  args:
    chdir: /tmp/isucon11-portal/supervisor
  environment:
    PATH: "/home/isucon/.cargo/bin:{{ ansible_env.PATH }}"
  shell: cargo build --release --bin isuxportal-supervisor

- name: "roles/bench.supervisor/tasks/main: Mkdir /home/isucon/bin"
  file:
    state: directory
    path: /home/isucon/bin
    owner: isucon
    group: isucon
    mode: "0755"

- name: "roles/bench.supervisor/tasks/main: Deploy isuxportal-supervisor"
  become_user: root
  copy:
    remote_src: yes
    src: /tmp/isucon11-portal/supervisor/target/release/isuxportal-supervisor
    dest: /home/isucon/bin/
    owner: isucon
    group: isucon
    mode: "0755"

- name: "roles/bench.supervisor/tasks/main: Deploy some files"
  become_user: root
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - etc/systemd/system/isuxportal-supervisor.service

- name: "roles/bench.supervisor/tasks/main: Enable isuxportal-supervisor.service"
  become_user: root
  systemd:
    daemon_reload: "yes"
    name: "isuxportal-supervisor.service"
    enabled: "yes"
