---
- name: "roles/bench/tasks/bench: Deploy isucon11-final benchmarker"
  become_user: isucon
  copy:
    src: /dev/shm/files-generated/benchmarker
    dest: /tmp/benchmarker
    owner: isucon
    group: isucon
  notify: "Restart isuxportal-supervisor.service"
